name: Release Orchestrator

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      - name: Fire sub-workflows
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish-cargo.yml

      - name: Trigger Builds
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-binaries.yml

      - name: Trigger PyPI
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish-pypi.yml

      - name: Trigger NPM
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish-npm.yml

      - name: Trigger Homebrew
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish-homebrew.yml
