name: Release Orchestrator

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Builds
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-binaries.yml
          token: ${{ secrets.WORKFLOW_PAT }}

      - name: Trigger PyPI Publish
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish-pypi.yml
          token: ${{ secrets.WORKFLOW_PAT }}

      - name: Fire Cargo Publish
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish-cargo.yml
          token: ${{ secrets.WORKFLOW_PAT }}

